version: '3.8'

services:
  backend:
    build: ./backend
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASS=2000@23
      - REDIS_HOST=redis
      - REDIS_PASS=senha_redis
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"

  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: whaticketwhaticketplus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2000@23
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  redis:
    image: redis
    command: redis-server --requirepass senha_redis
    ports:
      - "6379:6379"
